services:
  - type: worker
    name: smartplant-bot
    env: docker
    repo: https://github.com/vepr1991/smartplantv1_bot
    branch: main
    dockerfilePath: Dockerfile
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: FIREBASE_DB_URL
        sync: false
      - key: FIREBASE_KEY_JSON
        sync: false
